services:
  pitchdeck:
    build:
      context: /Users/np/kushify-pitchdeck
      dockerfile: /Users/np/kushify-docker/Dockerfile.main
    volumes:
      - /Users/np/kushify-pitchdeck:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  game:
    build:
      context: /Users/np/kushifycardgame
      dockerfile: /Users/np/kushify-docker/Dockerfile.play
    volumes:
      - /Users/np/kushifycardgame:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pitchdeck
      - game
