FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps && npm install react@18.3.1 react-dom@18.3.1

COPY . .

CMD ["npx", "vite", "--host", "0.0.0.0", "--port", "3000"]
